# Generated by Django 4.1.7 on 2023-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpj', upload_to=''),
        ),
    ]
