# Generated by Django 4.1.7 on 2023-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='Hackathon-Logo.png', upload_to=''),
        ),
    ]
